### ISSUE TITLE
Pulling docker images on prod env can lead to timeouts

### ISSUE THREAD

**Issue by gebele** [OpenRiskNet/home#18]
Evaluate reasons why pulling images from dockerhub in prod env takes so long in comparison to the dev env

**Comment by tdudgeon** [comment]
@gebele Can you provide more details?
I tried pulling some docker images on both environments and it was actually a bit faster on the uppmax region (where the prod site is running) compared to the hpc2n region (where the dev site is running).

**Comment by gebele** [comment]
ok no timeout message this time but anyway a quite long time to pull an image ?
12:34:20 PM pulling image
12:43:58 PM Successfully pulled image

**Comment by gebele** [comment]
in dev env it takes for the same image 1 sec !
4:45:38 PM pulling image
4:45:39 PM Successfully pulled image

**Comment by danyx23** [comment]
It takes long or not depending on whether the docker image has been pulled before on the node the pod is provision to. If it has been pulled before, then pull time is almost instantaenous. If not, then it takes however long it takes to download the multi-GB image from dockerhub. The zero-to-jupyterhub that deals with deploying jupyterhub on kubernetes has an optional service worker for this scenario that pulls the image on every node so that startups are faster. We can see if this can be translated to the openshift setup.

**Comment by gebele** [comment]
No this isn't the case for my image.

**Comment by GrahamDumpleton** [comment]
Are you first pulling external images on docker hub into internal image registry of OpenShift using ``oc import-image`` and then referencing via image stream name:tag rather than direct from external image registry. At least then each node is only pulling from internal image registry and should be a bit quicker.

Note that this approach will only work if image policy plugin is correctly set in master config. If it isn't you need to refer to image, including internal image registry name, from the internal image registry.

**Comment by tdudgeon** [comment]
Closing as this is no longer causing major problems.
