### ISSUE TITLE
ChemIDconvert error: 'No response from server'

### ISSUE THREAD

**Issue by DeniseSl22** [OpenRiskNet/home#31]
Dear reader,  from a colleague I recieved a link to your [API](http://orn-chemidconvert-chemidconvert.prod.openrisknet.org/v1/ui/#/). I wanted to use it to convert SMILES to InchiKey; however the response I am getting is: 
![image](https://user-images.githubusercontent.com/26277832/51107418-0e891c00-17ef-11e9-9266-74433d019658.png)

I'm not sure what is going wrong, I tried several examples (figure above shows SMILES for Ethanol)....
I've also tried two other API calls, which give me the same result (no response from server).

**Comment by danyx23** [comment]
Thanks for the report - I have just submitted a patch and the service should work correctly soon. The issue was that there are two instances of this service deployed, one within OpenRiskNet and the other at the DouglasConnect infrastructure. One is secured by https, the other isn't, and the swagger.yaml that is used to build the documentation was using the protocol information of the OpenRiskNet instance but pointed to the domain of the DouglasConnect installation

**Comment by danyx23** [comment]
Unfortunately the (old) swaggerUi version seems to have a bug that ignores the scheme. In this case you can't for now use the web interface of swaggerUi to run the queries, but if you use the curl command that is given for the request or the request URL in a python script or similar everything works as expected.
